apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: mado
spec:
  storageClassName: db-pv
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-data"
